# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NycfvMCiY3ah1kKZa-cjgplicTPgBhE2
"""

# Mapping of Persian to English key equivalents
mapping = {
    'Q': 'ض', 'W': 'ص', 'E': 'ث', 'R': 'ق', 'R': 'ف', 'Y': 'غ', 'U': 'ع', 'I': 'ه',
    'O': 'خ', 'P': 'ح', 'P': 'ج', ']': 'چ', '\\': 'پ', 'A': 'ش', 'S': 'س', 'D': 'ی',
    'F': 'ب', 'G': 'ل', 'H': 'ا', 'J': 'ت', 'K': 'ن', 'L': 'م', ';': 'ک', 'Z': 'ظ',
    'X': 'ط', 'C': 'ژ', 'V': 'ر', 'B': 'ذ', 'N': 'د', 'M': 'ئ', ',': 'و', '.': '.'
}

def convert_to_persian(input_string):
    output_string = ''
    for char in input_string:
        # Check if the character exists in the mapping
        if char.upper() in mapping:
            output_string += mapping[char.upper()]  # Add the corresponding Persian character
        else:
            output_string += char  # Keep the character as is if not found in the mapping
    return output_string

# Example
input_text = "sghl shl hldn,hvl o,f fhad"
converted_text = convert_to_persian(input_text)
print(converted_text)